 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: customercare
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: customercare
   template:
     metadata:
       labels:
         app: customercare
     spec:
       containers:
       - name: flasknode
         image: jayaseelan/customercare1
         imagePullPolicy: Always
         ports:
         - containerPort: 5000